name: Build & Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: rureous2210/rollback-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image with dynamic versioning (Git commit hash as version)
      - name: Build Docker image with commit hash version
        run: |
          VERSION=${GITHUB_SHA:0:7}  # Shortened commit SHA
          docker build -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          VERSION=${GITHUB_SHA:0:7}
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
